**Nesse notebook irá ser feita a coleta, limpeza e tratamento dos dados**

# Bibliotecas

Precisa-se do pandas para manusear as tabelas em dataframes e do pymysql para fazer a conexão com o banco mySQL

In [ ]:
!pip install pymysql

In [46]:
import pymysql
import pandas as pd

# conexão com o banco de dados

utilizou-se a IA para obter código que estabelece a conexão e registra as tabelas em dataframes




> prompt 1: quero que ele extraia e passe pare um dataframe

## conexão mySQL

In [5]:
# Dados de conexão
host = '185.213.26.130'
port = 6033
user = 'case_data_scientist'
password = 'UPDf/24bPQp8JuHC'
database = 'case_data_scientist'

# Conectando
conn = pymysql.connect(
    host=host,
    port=port,
    user=user,
    password=password,
    database=database
)

# Listar tabelas disponíveis
cursor = conn.cursor()
cursor.execute("SHOW TABLES;")
tabelas = cursor.fetchall()
print("Tabelas disponíveis no banco de dados:")
for t in tabelas:
    print("-", t[0])

Tabelas disponíveis no banco de dados:
- daumau
- desinstalacoes
- installs
- ratings_reviews

## transformando em dataframe

In [6]:
# Lista de tabelas que queremos carregar
tabelas = ['daumau', 'desinstalacoes', 'installs', 'ratings_reviews']

# Dicionário para armazenar os DataFrames
dfs = {}

# Loop para carregar cada tabela
for tabela in tabelas:
    df = pd.read_sql(f"SELECT * FROM {tabela}", conn)
    dfs[tabela] = df
    print(f"Tabela '{tabela}' carregada com shape: {df.shape}")

# Fecha a conexão
conn.close()

<ipython-input-6-2724695920>:9: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(f"SELECT * FROM {tabela}", conn)

Tabela 'daumau' carregada com shape: (41299, 4)
Tabela 'desinstalacoes' carregada com shape: (53188, 5)
Tabela 'installs' carregada com shape: (48150, 3)

<ipython-input-6-2724695920>:9: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(f"SELECT * FROM {tabela}", conn)

Tabela 'ratings_reviews' carregada com shape: (47155, 7)

# observando as tabelas

podemos agora observar as tabelas, tipos de dados, colunas, faltantes.

In [12]:
print(dfs['daumau'].info())
dfs['daumau']

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41299 entries, 0 to 41298
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   appId    41271 non-null  object
 1   date     41299 non-null  object
 2   dauReal  41105 non-null  float64
 3   mauReal  41279 non-null  float64
dtypes: float64(2), object(2)
memory usage: 1.3+ MB
None

               appId        date   dauReal    mauReal
0      com.app.33540  2024-01-01  393961.0  3643110.0
1      com.app.33540  2024-01-02  800448.0  3643040.0
2      com.app.31679  2024-01-01  157532.0  1349262.0
3      com.app.31679  2024-01-02  313847.0  1349317.0
4      com.app.77385  2024-01-01  239768.0  1934660.0
...              ...         ...       ...        ...
41294           None  2044-07-13  130203.0   578280.0
41295           None  2044-07-14    7412.0    36137.0
41296           None  2044-07-15   81544.0   854480.0
41297           None  2044-07-16   49957.0   173394.0
41298           None  2044-07-17    1932.0    16373.0

[41299 rows x 4 columns]

não faz sentido datas após a data de hoje, no case, 11 de junho de 2025

In [21]:
#confering dfs['daumau'] com date depois de 2025-06-11
hoje = pd.to_datetime('2025-06-11')
dfs['daumau'][dfs['daumau']['date'] > hoje]

               appId       date   dauReal    mauReal
41223  com.app.48916 2220-07-01    1007.0    15872.0
41224  com.app.97976 2220-07-02    6721.0    93668.0
41225  com.app.95194 2220-07-03  624826.0  5159034.0
41226  com.app.21397 2220-07-04   37606.0   393197.0
41227  com.app.60423 2220-07-05   55584.0   597227.0
...              ...        ...       ...        ...
41294           None 2044-07-13  130203.0   578280.0
41295           None 2044-07-14    7412.0    36137.0
41296           None 2044-07-15   81544.0   854480.0
41297           None 2044-07-16   49957.0   173394.0
41298           None 2044-07-17    1932.0    16373.0

[76 rows x 4 columns]

In [13]:
print(dfs['desinstalacoes'].info())
dfs['desinstalacoes']

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53188 entries, 0 to 53187
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   appId           53188 non-null  object
 1   date            53188 non-null  datetime64[ns]
 2   country         53188 non-null  object
 3   lang            53188 non-null  object
 4   predictionLoss  53188 non-null  int64
dtypes: datetime64[ns](1), int64(1), object(3)
memory usage: 2.0+ MB
None

               appId       date country lang  predictionLoss
0      com.app.71740 2024-01-01      br   pt            1463
1      com.app.33540 2024-01-01      br   pt            8170
2      com.app.19544 2024-01-01      br   pt           77048
3      com.app.77385 2024-01-01      br   pt            4497
4      com.app.31679 2024-01-01      br   pt            4287
...              ...        ...     ...  ...             ...
53183  com.app.47188 2024-09-08      br   pt           78127
53184  com.app.87411 2024-09-08      br   pt            1612
53185  com.app.96037 2024-09-08      br   pt            1712
53186  com.app.62031 2024-09-08      br   pt             828
53187  com.app.14811 2024-09-08      br   pt            1002

[53188 rows x 5 columns]

observando se há dados distintos nessas variáveis a seguir `country` e `lang` como não há, não há necessidade de mantê-las

In [15]:
print(dfs['desinstalacoes']['country'].value_counts())
print(dfs['desinstalacoes']['lang'].value_counts())

country
br    53188
Name: count, dtype: int64
lang
pt    53188
Name: count, dtype: int64

In [16]:
print(dfs['installs'].info())
dfs['installs']

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48150 entries, 0 to 48149
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   appid        48150 non-null  object
 1   date         48150 non-null  datetime64[ns]
 2   newinstalls  48150 non-null  int64
dtypes: datetime64[ns](1), int64(1), object(1)
memory usage: 1.1+ MB
None

               appid       date  newinstalls
0      com.app.86367 2024-01-01         1968
1      com.app.18711 2024-01-01         1364
2      com.app.36257 2024-01-01         7511
3      com.app.88509 2024-01-01        53137
4      com.app.93131 2024-01-01          137
...              ...        ...          ...
48145  com.app.43242 2024-09-09         1875
48146  com.app.98198 2024-09-09           25
48147  com.app.55537 2024-09-09           75
48148  com.app.83359 2024-09-09         2069
48149  com.app.65216 2024-09-09         1037

[48150 rows x 3 columns]

In [17]:
print(dfs['ratings_reviews'].info())
dfs['ratings_reviews']

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 47155 entries, 0 to 47154
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           47155 non-null  object
 1   appid          47155 non-null  object
 2   category       47155 non-null  object
 3   ratings        47155 non-null  float64
 4   daily_ratings  47155 non-null  float64
 5   reviews        47155 non-null  float64
 6   daily_reviews  47155 non-null  float64
dtypes: float64(4), object(3)
memory usage: 2.5+ MB
None

,date,appid,category,ratings,daily_ratings,reviews,daily_reviews
0,2024-01-01,com.app.40009,OTHERS,63500.0,5.0,25251.0,0.0
1,2024-01-01,com.app.88516,OTHERS,2440.0,0.0,312.0,0.0
2,2024-01-01,com.app.64634,TRAVEL_AND_LOCAL,536.0,0.0,331.0,0.0
3,2024-01-01,com.app.78470,SHOPPING,97924.0,7.0,27241.0,23.0
4,2024-01-01,com.app.36433,FINANCE,678.0,0.0,414.0,0.0
...,...,...,...,...,...,...,...
47150,2024-09-30,com.app.14509,FINANCE,1426039.0,452.0,618170.0,108.0
47151,2024-09-30,com.app.18711,BUSINESS,63943.0,28.0,16929.0,14.0
47152,2024-09-30,com.app.14811,FINANCE,8863.0,2.0,4938.0,2.0
47153,2024-09-30,com.app.20103,FINANCE,1542.0,0.0,1152.0,0.0
47154,2024-09-30,com.app.74881,FINANCE,29642.0,36.0,12931.0,9.0

o mesmo verificando a distribuição das categorias. Nesse caso, por agora, como está distribuido, é interessante manter

In [18]:
dfs['ratings_reviews']['category'].value_counts()

category
FINANCE             18667
OTHERS              11495
SHOPPING             7981
BUSINESS             4184
TRAVEL_AND_LOCAL     3123
FOOD_AND_DRINK       1705
Name: count, dtype: int64

# Tratamento das tabelas

## copiar para DFs singulares

primeiramente vamos passar todos para DFs individuais para melhor manuseio

In [32]:
df_daumau = dfs['daumau']
df_desinstalacoes = dfs['desinstalacoes']
df_installs = dfs['installs']
df_ratings_reviews = dfs['ratings_reviews']

## converter para datetime

garantindo que todos tem o mesmo formato de data

In [39]:
#conferindo se há date acima de hoje em outros
hoje = pd.to_datetime('2025-06-11')
print('em desinstalações', len(df_desinstalacoes[df_desinstalacoes['date'] > hoje]))
print('em installs', len(df_installs[df_installs['date'] > hoje]))
print('em ratings_reviews', len(df_ratings_reviews[df_ratings_reviews['date'] > hoje]))

em desinstalações 0
em installs 0
em ratings_reviews 0

In [33]:
#converter datas de df_daumau e df_ratings_reviews em datetime64[ns]
df_daumau['date'] = pd.to_datetime(df_daumau['date'])
df_ratings_reviews['date'] = pd.to_datetime(df_ratings_reviews['date'])

#filtrar dados depois de 2025-06-11
date_threshold = pd.to_datetime('2025-06-11')
df_daumau = df_daumau[df_daumau['date'] <= date_threshold]

#conferir
print(dfs['daumau'].info())
print(dfs['ratings_reviews'].info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41299 entries, 0 to 41298
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   appId    41271 non-null  object
 1   date     41299 non-null  datetime64[ns]
 2   dauReal  41105 non-null  float64
 3   mauReal  41279 non-null  float64
dtypes: datetime64[ns](1), float64(2), object(1)
memory usage: 1.3+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 47155 entries, 0 to 47154
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           47155 non-null  datetime64[ns]
 1   appid          47155 non-null  object
 2   category       47155 non-null  object
 3   ratings        47155 non-null  float64
 4   daily_ratings  47155 non-null  float64
 5   reviews        47155 non-null  float64
 6   daily_reviews  47155 non-null  float64
dtypes: datetime64[ns](1), float64(4), object(2)
memory usage: 2.5+ MB
None

## remover colunas

`mauReal` não é a target, então ela pode atrapalhar o modelo pela semelhança. E `country` e `lang` são de apenas um valor sem variabilidade

In [34]:
#remover colunas country e lang de df_desinstalacoes
df_desinstalacoes = df_desinstalacoes.drop(columns=['country', 'lang'])

#remover mauReal de df_daumau
df_daumau = df_daumau.drop(columns=['mauReal'])

#conferindo
print(df_desinstalacoes.columns)
print(df_daumau.columns)

Index(['appId', 'date', 'predictionLoss'], dtype='object')
Index(['appId', 'date', 'dauReal'], dtype='object')

## remover duplicados

In [35]:
#renomeando colunas de 'appid' para 'appId'
df_installs = df_installs.rename(columns={'appid': 'appId'})
df_ratings_reviews = df_ratings_reviews.rename(columns={'appid': 'appId'})

# remover duplicados em appId e date de todos
df_daumau = df_daumau.drop_duplicates(subset=['appId', 'date'])
df_desinstalacoes = df_desinstalacoes.drop_duplicates(subset=['appId', 'date'])
df_installs = df_installs.drop_duplicates(subset=['appId', 'date'])
df_ratings_reviews = df_ratings_reviews.drop_duplicates(subset=['appId', 'date'])

#resetar o index de todos
df_daumau = df_daumau.reset_index(drop=True)
df_desinstalacoes = df_desinstalacoes.reset_index(drop=True)
df_installs = df_installs.reset_index(drop=True)
df_ratings_reviews = df_ratings_reviews.reset_index(drop=True)

#checando se tem duplicado em appId e date
print(df_daumau.duplicated(subset=['appId', 'date']).sum())
print(df_desinstalacoes.duplicated(subset=['appId', 'date']).sum())
print(df_installs.duplicated(subset=['appId', 'date']).sum())
print(df_ratings_reviews.duplicated(subset=['appId', 'date']).sum())

0
0
0
0

## analisando faltantes

In [36]:
#info de todos os nulos
print("Nulos em daumau:")
print(df_daumau.isnull().sum(), '\n')
print("Nulos em desinstalacoes:")
print(df_desinstalacoes.isnull().sum(), '\n')
print("Nulos em installs:")
print(df_installs.isnull().sum(), '\n')
print("Nulos em ratings_reviews:")
print(df_ratings_reviews.isnull().sum())

Nulos em daumau:
appId        0
date         0
dauReal    194
dtype: int64

Nulos em desinstalacoes:
appId             0
date              0
predictionLoss    0
dtype: int64

Nulos em installs:
appId          0
date           0
newinstalls    0
dtype: int64

Nulos em ratings_reviews:
date             0
appId            0
category         0
ratings          0
daily_ratings    0
reviews          0
daily_reviews    0
dtype: int64

como apenas `dauReal` apresentou nulos, e ela é nossa target, iremos remover os nulos

In [37]:
#remover nulos em daumau
df_daumau = df_daumau.dropna()

#resetar_index
df_daumau = df_daumau.reset_index(drop=True)

#conferindo
df_daumau.isnull().sum()

appId      0
date       0
dauReal    0
dtype: int64

# merge

iremos agora unir as tabelas com intuito de agregar informações à tabela com a target, pois nos próximos passos desse projeto, será avaliado quais métricas e variáveis influenciam na target, o que será relevante para o modelo.

## fazendo o merge

In [49]:
merged_df = df_daumau.merge(df_desinstalacoes, on=['appId', 'date'], how='left')
merged_df = merged_df.merge(df_installs, on=['appId', 'date'], how='left')
merged_df = merged_df.merge(df_ratings_reviews, on=['appId', 'date'], how='left')

#ordenar por data
merged_df = merged_df.sort_values(by='date')

#resetar o index
merged_df = merged_df.reset_index(drop=True)

print("Shape:", merged_df.shape)
merged_df.head()

Shape: (40876, 10)

,appId,date,dauReal,predictionLoss,newinstalls,category,ratings,daily_ratings,reviews,daily_reviews
0,com.app.68335,1912-02-01,8627.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,com.app.47280,1912-02-02,9695892.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,com.app.22262,1912-02-03,97263.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,com.app.64353,1912-02-04,269402.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,com.app.92275,1912-02-05,69026.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [50]:
#remover todos com data anterior a 2008-07-10 (criação da app store)
merged_df = merged_df[merged_df['date'] >= '2008-07-10']

#resetar o index
merged_df = merged_df.reset_index(drop=True)

print("Shape:", merged_df.shape)
merged_df.head()

Shape: (40851, 10)

,appId,date,dauReal,predictionLoss,newinstalls,category,ratings,daily_ratings,reviews,daily_reviews
0,com.app.17806,2024-01-01,163431.0,27040.0,5955.0,OTHERS,682224.0,154.0,168471.0,57.0
1,com.app.80610,2024-01-01,611934.0,112183.0,10890.0,BUSINESS,893104.0,191.0,359446.0,120.0
2,com.app.62062,2024-01-01,22618.0,4554.0,871.0,SHOPPING,52665.0,1.0,1845.0,2.0
3,com.app.34216,2024-01-01,1729.0,1786.0,NaN,NaN,NaN,NaN,NaN,NaN
4,com.app.26790,2024-01-01,6245.0,1758.0,679.0,FINANCE,50415.0,0.0,26728.0,1.0

## tratando os nulos

In [51]:
#contabilizando nulos
merged_df.isnull().sum()

appId                0
date                 0
dauReal              0
predictionLoss     127
newinstalls       2569
category          2143
ratings           2143
daily_ratings     2143
reviews           2143
daily_reviews     2143
dtype: int64

como não há nulos na target. E as com faltantes pode siginificar que não houve a ocorrência para tal app tal dia ou a taxa estava zero, iremos zerar todos os nulos, exceto a variável categórica que será descrita com uma informação equivalente como `DESCONHECIDO`

In [52]:
#preencher nulos em category como 'DESCONHECIDO'
merged_df['category'] = merged_df['category'].fillna('DESCONHECIDO')

#preencher todoas as numéricas com 0
numericas = ['predictionLoss', 'newinstalls', 'ratings', 'daily_ratings', 'reviews', 'daily_reviews']
merged_df[numericas] = merged_df[numericas].fillna(0)

#conferindo
print(merged_df.isnull().sum())
print(merged_df.info())

appId             0
date              0
dauReal           0
predictionLoss    0
newinstalls       0
category          0
ratings           0
daily_ratings     0
reviews           0
daily_reviews     0
dtype: int64
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40851 entries, 0 to 40850
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   appId           40851 non-null  object
 1   date            40851 non-null  datetime64[ns]
 2   dauReal         40851 non-null  float64
 3   predictionLoss  40851 non-null  float64
 4   newinstalls     40851 non-null  float64
 5   category        40851 non-null  object
 6   ratings         40851 non-null  float64
 7   daily_ratings   40851 non-null  float64
 8   reviews         40851 non-null  float64
 9   daily_reviews   40851 non-null  float64
dtypes: datetime64[ns](1), float64(7), object(2)
memory usage: 3.1+ MB
None

## salvar

pelo notebook ser desenvolvido em Google Colab, o salvamento neste momento será feito com o drive mountado

In [53]:
#mount drive
from google.colab import drive
drive.mount('/content/drive')

#salvar em .csv no drive
merged_df.to_csv('/content/drive/MyDrive/Codes/Rankmyapp/data.csv', index=False)

Mounted at /content/drive